const nigerianStates = [
  { title: "State of residence", value: "" },
  { title: "Abia", value: "Abia" },
  { title: "Adamawa", value: "Adamawa" },
  { title: "Akwa Ibom", value: "Akwa Ibom" },
  { title: "Anambra", value: "Anambra" },
  { title: "Bauchi", value: "Bauchi" },
  { title: "Bayelsa", value: "Bayelsa" },
  { title: "Benue", value: "Benue" },
  { title: "Borno", value: "Borno" },
  { title: "Cross River", value: "Cross River" },
  { title: "Delta", value: "Delta" },
  { title: "Ebonyi", value: "Ebonyi" },
  { title: "Edo", value: "Edo" },
  { title: "Ekiti", value: "Ekiti" },
  { title: "Enugu", value: "Enugu" },
  { title: "FCT", value: "FCT" },
  { title: "Gombe", value: "Gombe" },
  { title: "Imo", value: "Imo" },
  { title: "Jigawa", value: "Jigawa" },
  { title: "Kaduna", value: "Kaduna" },
  { title: "Kano", value: "Kano" },
  { title: "Katsina", value: "Katsina" },
  { title: "Kebbi", value: "Kebbi" },
  { title: "Kogi", value: "Kogi" },
  { title: "Kwara", value: "Kwara" },
  { title: "Lagos", value: "Lagos" },
  { title: "Nasarawa", value: "Nasarawa" },
  { title: "Niger", value: "Niger" },
  { title: "Ogun", value: "Ogun" },
  { title: "Ondo", value: "Ondo" },
  { title: "Osun", value: "Osun" },
  { title: "Oyo", value: "Oyo" },
  { title: "Plateau", value: "Plateau" },
  { title: "Rivers", value: "Rivers" },
  { title: "Sokoto", value: "Sokoto" },
  { title: "Taraba", value: "Taraba" },
  { title: "Yobe", value: "Yobe" },
  { title: "Zamfara", value: "Zamfara" }
];

export default nigerianStates;
